# Setup
title:        StembaOS
tagline:      Sistem Operasi untuk pelajar SMA/SMK
baseurl:      ""
paginate:     1
locale:       "id"

# About/contact
author:
  name:       StembaOS Developer
  url:        https://stembaos.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown